### ISSUE TITLE
Options["Training"] is read before it can be assigned through uci if Threads option precedes Training

### ISSUE THREAD

**Issue by Sopel97** [nodchip/Stockfish#119]
Found by linox. I'm posting this verbatim from discord.

There is a bug in the use of option Options["Training"]. Default value is false, when user sends the command
setoption name training value true it will not set to true because it is called under Search::init() at https://github.com/nodchip/Stockfish/blob/4cc98d80f8a5e6eb0b716a47bc4eb8b877b5a979/src/search.cpp#L199
To fix this issue the training = Options["Training"]; can be called under void MainThread::search() at https://github.com/nodchip/Stockfish/blob/4cc98d80f8a5e6eb0b716a47bc4eb8b877b5a979/src/search.cpp#L219

**Comment by nodchip** [comment]
I realized that the suggested idea does not fix the issue because MainThread::search() is not called on `gensfen` command.  Instead of it, I suggest the following way:

- Set the same value to the default value of the global variable and the UCI option.
- Set the value of the global variable on a UCI option callback function.

@Sopel97 Could you please review #126?
