### ISSUE TITLE
Gensfen move randomisation as UCI options

### ISSUE THREAD

**Issue by NightlyKing** [nodchip/Stockfish#33]
It would really help to be able to use options such as random_move_like_apery etc. via UCI. That would allow for generating fens with cutechss-cli which would make it much easier for fishtest-like platforms to distribute game generation and it would further enable us to use the games for other ML projects as well.

**Comment by nodchip** [comment]
When I develop my shogi engine, I often implement options as USI options.  (USI is the Shogi version of the UCI.)  But I didn't do it  in Stockfish+NNUE because the development cost is slightly high.  And it takes a long time to port latest changes in YaneuraOu.
If many user agree with your suggestion, I will think about it again.

**Comment by Sopel97** [comment]
I think this should be closed. There has been no other requests for this feature and considering the amount of work required it's not worth.
